schema-version: 1.0

var:
  version:
  ifname: eth1
  memory: 512
  cpus: 1
  ova:

#bootstrap:
#  - url:
#      from: https://s3.eu-west-3.amazonaws.com/xbee.repository/providers/{{ .piper.os }}_{{ .piper.arch }}/virtualbox.tar.gz
#      to: "{{ .piper.cache }}/s3.eu-west-3.amazonaws.com/xbee.repository/providers/{{ .piper.os }}_{{ .piper.arch }}"

provision:
  - url:
      from: https://download.virtualbox.org/virtualbox/{{ .product.version }}/VBoxGuestAdditions_{{ .product.version }}.iso
      to: /tmp
      unpack: false
      after: "{{ .templates }}/install.sh"

command:
  execute: "{{ .piper.cache }}/s3.eu-west-3.amazonaws.com/xbee.repository/providers/{{ .piper.os }}_{{ .piper.arch }}/virtualbox"



  