schema-version: 1.0
name: virtualbox

var:
  version:
  ifname: eth1
  memory: 512
  cpus: 1

const:
  alphabet: abcdefgh #used for device mapping. first volume is map to b, second to c ...
  prefix: s #used for device mapping -> /dev/sd[x]


provision:
  - url:
      from: https://download.virtualbox.org/virtualbox/{{ version }}/VBoxGuestAdditions_{{ version }}.iso
      to: /tmp
      unpack: false
  - url:
      from: https://s3.eu-west-3.amazonaws.com/xbee.io/providers/linux_amd64/guest
      to: /opt/piper
      unpack: false
      after: chmod u+x /opt/piper/guest

  - shell: install.sh
  - shell: nmcli connection add type ethernet con-name pipernet ifname {{ ifname }}
  - shell: hosts.sh
  - shell: /opt/piper/guest provision {{ alphabet }} {{ prefix }}

up:
  - shell: /opt/piper/guest mount {{ alphabet }} {{ prefix }}
      

